export const SALT_ROUNDS = 10;
export const AUTH_USER_EXISTS = 'User with this email already exists';
export const AUTH_USER_NOT_FOUND = 'User not found';
export const AUTH_USER_FOUND = 'User found';
export const AUTH_USER_PASSWORD_WRONG = 'User password is wrong';
export const AUTH_USER_LOGIN_SUCCESS = 'User has been successfully logged';
export const AUTH_USER_LOGIN_ERROR = 'Password or Login is wrong';
export const AUTH_USER_CREATED = 'New user has been successfully created';
export const AUTH_EMAIL_NOT_VALID = 'Email is not valid';
